#!/bin/sh

echo ---Dirty guard hook start---

if ! command -v python &> /dev/null
then
    python3 dirt_rejecter.py
    ret=$?
    if [ $ret -ne 0 ]; then
        exit $ret
    fi
else
    python dirt_rejecter.py
    ret=$?
    if [ $ret -ne 0 ]; then
        exit $ret
    fi
fi




if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

echo ---Dirty guard hook ended---
